In [ ]:
%cd /content/drive/My Drive/Pooling

/content/drive/My Drive/Pooling


In [ ]:
%cd sopool-gnns/

/content/drive/My Drive/Pooling/sopool-gnns


In [ ]:
!python main.py --dataset COLLAB  --device 0 --fold_idx 0 --batch_size 32 --hidden_dim 64 --degree_as_tag

loading data
# classes: 3
# maximum node tag: 367
# data: 5000
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
epoch: 1: 100% 50/50 [00:04<00:00, 11.91batch/s]
loss training: 11.448489
accuracy train: 0.727778 test: 0.714000

Parameter containing:
tensor([0., 0., 0., 0.], device='cuda:0', requires_grad=True)
epoch: 2: 100% 50/50 [00:02<00:00, 19.33batch/s]
loss training: 4.378169
accuracy train: 0.720222 test: 0.684000

Parameter containing:
tensor([0., 0., 0., 0.], device='cuda:0', requires_

In [ ]:
!python main.py --dataset COLLAB  --device 0 --fold_idx 0 --batch_size 32 --hidden_dim 64 --degree_as_tag

loading data
# classes: 3
# maximum node tag: 367
# data: 5000
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
epoch: 1: 100% 50/50 [00:03<00:00, 16.18batch/s]
loss training: 140.752469
accuracy train: 0.418444 test: 0.412000

Parameter containing:
tensor([0., 0., 0., 0.], device='cuda:0', requires_grad=True)
epoch: 2: 100% 50/50 [00:02<00:00, 17.62batch/s]
loss training: 257.803943
accuracy train: 0.662667 test: 0.626000

Parameter containing:
tensor([0., 0., 0., 0.], device='cuda:0', requir